'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent,useState } from 'react';
import { ArrowRightIcon, CheckIcon, SparkleIcon } from '@/app/components/Icons';

export default function RegisterPage(){
  const router=useRouter();const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const d=new FormData(event.currentTarget);try{const r=await fetch('/api/session/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:d.get('name'),email:d.get('email'),password:d.get('password')})});if(!r.ok){const p=await r.json().catch(()=>null);setError(p?.error?.message??'Registration failed');setBusy(false);return}router.push('/');router.refresh()}catch{setError('Connection problem. Try again.');setBusy(false)}}
  const benefits=['Save titles without losing them','Keep one reading stack across devices','Publish accountable reader reviews','Track every order from pending to complete'];
  return <main className="page-shell auth-grid pb-28 pt-10 md:pb-16">
    <section className="hidden lg:block"><p className="eyebrow flex items-center gap-2"><SparkleIcon size={14}/> Build your reading memory</p><h1 className="display-title mt-5 max-w-3xl">A bookstore that remembers <span className="text-gradient">what matters to you.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">Create one private reader identity for your saved shelf, reviews, cart and complete order history.</p><div className="mt-9 grid max-w-xl gap-3">{benefits.map((item,index)=><div key={item} className="editorial-card flex items-center gap-4 p-4"><span aria-hidden="true" className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-emerald-400/10 text-emerald-300"><CheckIcon size={14}/></span><span className="flex-1 text-sm font-semibold text-slate-300">{item}</span><span className="text-[10px] font-black tracking-[.14em] text-slate-700">0{index+1}</span></div>)}</div></section>
    <section className="surface mx-auto w-full max-w-md rounded-[1.9rem] p-6 sm:p-8"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl border border-violet-200/20 bg-gradient-to-br from-violet-400 to-amber-200 font-black text-slate-950">BH</div><span className="chip"><span className="status-dot" aria-hidden="true"/> Free account</span></div><p className="section-kicker mt-7">New reader</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Create your BookHaven.</h2><p className="mt-2 text-sm leading-6 text-slate-500">Private, account-bound and ready for your first saved edition.</p><form onSubmit={submit} aria-busy={busy} className="mt-7 space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-slate-600">Name</span><input name="name" required minLength={2} maxLength={120} autoComplete="name" placeholder="Your name" className="field" /></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-slate-600">Email</span><input name="email" type="email" inputMode="email" required autoComplete="email" placeholder="you@example.com" className="field" /></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-slate-600">Password</span><input name="password" type="password" required minLength={8} autoComplete="new-password" placeholder="At least 8 characters" className="field" /></label>{error?<p role="alert" aria-live="assertive" aria-atomic="true" className="notice notice--error">{error}</p>:null}<button type="submit" disabled={busy} className="button button--primary w-full">{busy?'Creating your library…':<>Create reader account <ArrowRightIcon size={17}/></>}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already a reader? <Link href="/login" className="font-bold text-amber-200 hover:underline">Sign in</Link></p></section>
  </main>
}
