services:
  - type: web
    name: bookhaven-free
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm run build:free
    startCommand: npm run start:free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: NEXT_PUBLIC_SITE_URL
        value: https://bookhaven-free.onrender.com
      - key: NODE_ENV
        value: production
      - key: INTERNAL_API_URL
        value: http://127.0.0.1:3001/api/v1
      - key: BACKEND_PORT
        value: "3001"
      - key: AUTO_SEED
        value: "true"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: http://127.0.0.1:3001
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
