'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent,useState } from 'react';
import { ArrowRightIcon, BookIcon, ShieldIcon, SparkleIcon } from '@/app/components/Icons';

export default function LoginPage(){
  const router=useRouter();const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{const r=await fetch('/api/session/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password')})});if(!r.ok){const p=await r.json().catch(()=>null);setError(p?.error?.message??'Login failed');setBusy(false);return}router.push('/');router.refresh()}catch{setError('Connection problem. Try again.');setBusy(false)}}
  return <main className="page-shell auth-grid pb-28 pt-10 md:pb-16">
    <section className="hidden lg:block"><p className="eyebrow flex items-center gap-2"><SparkleIcon size={14}/> Your private reading space</p><h1 className="display-title mt-5 max-w-3xl">Come back to the books you <span className="text-gradient">kept thinking about.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">One account connects your saved shelf, reading stack, reviews and order journal across devices.</p><div className="mt-9 grid max-w-xl grid-cols-2 gap-3"><div className="editorial-card p-5"><ShieldIcon className="text-amber-200"/><strong className="mt-4 block">HTTP-only session</strong><p className="mt-1 text-xs leading-5 text-slate-500">Authentication tokens stay outside client-side JavaScript.</p></div><div className="editorial-card p-5"><BookIcon className="text-violet-300"/><strong className="mt-4 block">Reader-bound library</strong><p className="mt-1 text-xs leading-5 text-slate-500">Saved titles, cart and orders follow the account rather than one device.</p></div></div></section>
    <section className="surface mx-auto w-full max-w-md rounded-[1.9rem] p-6 sm:p-8"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl border border-amber-100/20 bg-gradient-to-br from-amber-200 to-violet-400 font-black text-slate-950">BH</div><span className="chip"><span className="status-dot" aria-hidden="true"/> Reader access</span></div><p className="section-kicker mt-7">Welcome back</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Open your BookHaven.</h2><p className="mt-2 text-sm leading-6 text-slate-500">Sign in and pick up from the exact shelf you left.</p><form onSubmit={submit} aria-busy={busy} className="mt-7 space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-slate-600">Email</span><input name="email" type="email" inputMode="email" autoComplete="email" required placeholder="you@example.com" className="field" /></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-slate-600">Password</span><input name="password" type="password" autoComplete="current-password" required placeholder="Your password" className="field" /></label>{error?<p role="alert" aria-live="assertive" aria-atomic="true" className="notice notice--error">{error}</p>:null}<button type="submit" disabled={busy} className="button button--primary w-full">{busy?'Opening your library…':<>Sign in <ArrowRightIcon size={17}/></>}</button></form><p className="mt-6 text-center text-sm text-slate-500">New here? <Link href="/register" className="font-bold text-amber-200 hover:underline">Create your reader account</Link></p></section>
  </main>
}
