import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { env } from './config/env';
import { errorHandler } from './middleware/error-handler';
import { notFound } from './middleware/not-found';
import { requestContext } from './middleware/request-context';
import { apiRouter } from './routes';

export const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(requestContext);
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGIN.split(',').map((origin) => origin.trim()), credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: false, limit: '1mb' }));
app.use(rateLimit({ windowMs: 60_000, limit: env.NODE_ENV === 'test' ? 10_000 : 300, standardHeaders: 'draft-8' }));
app.use('/api/v1/auth', rateLimit({ windowMs: 60_000, limit: env.NODE_ENV === 'test' ? 10_000 : 30, standardHeaders: 'draft-8', skipSuccessfulRequests: true }));
app.use('/api/v1', apiRouter);
app.use(notFound);
app.use(errorHandler);
