'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import type { CartItem } from '@/lib/types';
import EmptyState from '@/app/components/EmptyState';
import { BagIcon, MinusIcon, PlusIcon, ShieldIcon, TrashIcon } from '@/app/components/Icons';

type Cart = { items: CartItem[]; subtotal: number };
export default function CartPage() {
  const [cart, setCart] = useState<Cart | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = useCallback(async () => { const r = await fetch('/api/backend/cart', { cache: 'no-store' }); if (r.status === 401) { setError('Please sign in to view your cart.'); setCart(null); return; } if (!r.ok) { setError('Could not load your cart.'); return; } const p = await r.json(); setCart(p.data); setError(''); }, []);
  useEffect(() => { void load(); }, [load]);
  async function mutate(id: string, options: RequestInit) { setBusy(id); const r = await fetch(`/api/backend/cart/items/${id}`, options); if (!r.ok) { const p = await r.json().catch(() => null); setError(p?.error?.message ?? 'Could not update cart.'); } await load(); window.dispatchEvent(new Event('bookhaven:cart-changed')); setBusy(''); }
  const count = cart?.items.reduce((n, i) => n + i.quantity, 0) ?? 0;
  return <main className="page-shell pb-28 pt-12 md:pb-20 md:pt-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">Your selection</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">A small stack before the next chapter.</h1><p className="mt-3 text-sm text-slate-500">{count} item{count === 1 ? '' : 's'} reserved for checkout.</p></div><Link href="/" className="button button--ghost">Keep browsing</Link></div>
    {error ? <div className="notice notice--error mt-7">{error} {error.startsWith('Please') ? <Link href="/login" className="ml-2 font-bold underline">Sign in</Link> : null}</div> : null}
    {cart ? cart.items.length ? <div className="mt-9 grid gap-7 lg:grid-cols-[1fr_340px]"><section className="space-y-3">{cart.items.map(item => <article key={item.book._id} className="glass flex gap-4 rounded-2xl p-4 sm:items-center"><div className="cover-mini">{item.book.coverUrl ? <img src={item.book.coverUrl} alt="" className="h-full w-full object-cover" referrerPolicy="no-referrer"/> : <div className="grid h-full place-items-center">📖</div>}</div><div className="min-w-0 flex-1"><Link href={`/books/${item.book.slug}`} className="font-black hover:text-amber-100">{item.book.title}</Link><p className="mt-1 text-xs text-slate-500">{item.book.author} · ${item.unitPrice.toFixed(2)} each</p></div><div className="flex items-center gap-1 rounded-xl border border-white/10 bg-black/20 p-1"><button disabled={busy === item.book._id || item.quantity <= 1} onClick={() => mutate(item.book._id, { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({quantity:item.quantity-1}) })} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-white/5" aria-label="Decrease quantity"><MinusIcon size={15}/></button><span className="w-7 text-center text-sm font-black">{item.quantity}</span><button disabled={busy === item.book._id || item.quantity >= item.book.stock} onClick={() => mutate(item.book._id, { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({quantity:item.quantity+1}) })} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-white/5" aria-label="Increase quantity"><PlusIcon size={15}/></button></div><button disabled={busy === item.book._id} onClick={() => mutate(item.book._id,{method:'DELETE'})} className="button button--ghost !min-h-9 !px-2.5" aria-label={`Remove ${item.book.title}`}><TrashIcon size={15}/></button></article>)}</section><aside className="surface h-fit rounded-[1.5rem] p-6 lg:sticky lg:top-28"><p className="section-kicker">Summary</p><div className="mt-5 flex items-center justify-between text-sm text-slate-400"><span>{count} items</span><span>Shipping calculated offline</span></div><div className="mt-5 flex items-end justify-between border-t border-white/10 pt-5"><span className="text-sm text-slate-400">Subtotal</span><strong className="text-3xl tracking-tight">${cart.subtotal.toFixed(2)}</strong></div><Link href="/checkout" className="button button--primary mt-6 w-full"><BagIcon size={17}/> Continue to checkout</Link><p className="mt-4 flex items-center gap-2 text-xs leading-5 text-slate-600"><ShieldIcon size={15}/> Stock is validated again when the order is placed.</p></aside></div> : <div className="mt-10"><EmptyState title="Your cart is beautifully empty" description="Explore the library and add something worth making time for." icon={<BagIcon size={27}/>} /></div> : null}
  </main>;
}
